name: 'update-version'
description: 'set version, if release generate changelog'
branding:
  icon: 'git-commit'
  color: 'red'
inputs:
  release:
    description: "publish"
    default: false
outputs:
  version:
    description: "Generated version"
    value: ${{ steps.convco.outputs.version }}
runs:
  using: "composite"
  
  steps:

    - name: Install tools
      shell: bash
      run: |
        sudo apt install -y libarchive-tools

    - name: Install convco
      shell: bash
      run: |
        curl -#L https://github.com/convco/convco/releases/download/v0.5.1/convco-ubuntu.zip | bsdtar -xf- - -C /usr/local/bin/
        chmod a+x /usr/local/bin/convco
      
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: convco
      shell: bash

        git config user.name github-actions
        git config user.email github-actions@github.com

        if [[ ${{ github.ref == 'refs/heads/main' }} ]]
        then
          VERSION=$(convco version -C ${{ github.workspace }}/repo --bump)
          git tag $VERSION
          convco changelog > CHANGELOG.md
          git add CHANGELOG.md
          git commit -am "chore: Updating changelog"
          git push
          git push origin $VERSION
          echo ":balloon: New release version: $VERSION" >> $GITHUB_STEP_SUMMARY
        else
          VERSION=$(convco version -C ${{ github.workspace }}/repo --prerelease dev --bump)
          echo ":balloon: New dev version: $VERSION" >> $GITHUB_STEP_SUMMARY
        fi

      # if: ${{ github.ref == 'refs/heads/main' }}
      # run: |

      #   git config user.name github-actions
      #   git config user.email github-actions@github.com

      #   VERSION="0.1"

      #   # if [[ ${{ inputs.release }} == "true" ]]
      #   if [[ ${{ github.ref == 'ref/head/main' }} ]]
      #   then
      #   #   VERSION=$(convco version -C ${{ github.workspace }}/repo --bump)
      #   #   git tag $VERSION
      #   #   convco changelog > CHANGELOG.md
      #   #   git add CHANGELOG.md
      #   #   git commit -am "chore: Updating changelog"
      #   #   git push
      #   #   git push origin $VERSION
      #     echo ":balloon: New release version: $VERSION" >> $GITHUB_STEP_SUMMARY
      #   else
      #   #   VERSION=$(convco version -C ${{ github.workspace }}/repo --prerelease dev --bump)
      #     echo ":balloon: New dev version: $VERSION" >> $GITHUB_STEP_SUMMARY
      #   fi
        

      echo "version=$VERSION" >> $GITHUB_OUTPUT