name: 'new-version'
description: 'set version and generate changelog'
branding:
  icon: 'git-commit'
  color: 'red'
inputs:
  release:
    description: "ready for release"
    default: false
outputs:
  version:
    description: "Version released"
    value: ${{ steps.convco.outputs.version }}
runs:
  using: "composite"
  steps:

    - name: Install tools
      run: sudo apt install -y libarchive-tools

    - name: Install convco
      curl -OL https://github.com/convco/convco/releases/latest/download/convco-deb.zip
      unzip convco-deb.zip
      sudo dpkg -i convco*.deb

    - uses: actions/checkout@v4
      with:
        path: "repo"
        fetch-depth: 0

    - id: convco
      run: |

        if [[ ${{ inputs.release }} == "true" ]]
        then
          VERSION=$(convco version -C ${{ github.workspace }}/repo --bump)
        else
          VERSION=$(convco version -C ${{ github.workspace }}/repo --prerelease dev --bump)
        fi

        echo ":balloon: Got a new version: $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash